<template>
  <div class="report-viewer-page">
    <div class="page-header mb-4">
      <div class="header-left">
        <h2 class="fw-bold"><i class="bi bi-file-earmark-bar-graph me-2"></i>Report Viewer</h2>
        <p class="text-muted mb-0">Select and generate system reports</p>
      </div>
      <div class="header-right d-flex gap-2">
        <button class="btn btn-outline-primary" @click="printReport" :disabled="!reportData">
          <i class="bi bi-printer me-1"></i> Print
        </button>
        <div class="dropdown">
          <button class="btn btn-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" :disabled="!reportData">
            <i class="bi bi-download me-1"></i> Export
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#" @click.prevent="exportReport('excel')"><i class="bi bi-file-earmark-excel me-2"></i>Excel (.xlsx)</a></li>
            <li><a class="dropdown-item" href="#" @click.prevent="exportReport('pdf')"><i class="bi bi-file-earmark-pdf me-2"></i>PDF (.pdf)</a></li>
          </ul>
        </div>
      </div>
    </div>

    <!-- REPORT SELECTOR & FILTERS -->
    <div class="card shadow-sm border-0 mb-4 overflow-visible">
      <div class="card-body">
        <div class="row g-3 align-items-end">
          <div class="col-md-4">
            <label class="form-label small fw-bold text-muted text-uppercase">Select Report Type</label>
            <select v-model="selectedReportId" class="form-select" @change="onReportSelect">
              <option value="" disabled>Choose a report configuration...</option>
              <option v-for="r in reportConfigs" :key="r.reportId" :value="r.reportId">{{ r.reportName }}</option>
            </select>
          </div>
          
          <template v-if="selectedReportConfig">
            <div class="col-md-3">
              <label class="form-label small fw-bold text-muted text-uppercase">Search in Results</label>
              <div class="input-group">
                <span class="input-group-text bg-white border-end-0"><i class="bi bi-search"></i></span>
                <input v-model="searchQuery" type="text" class="form-control border-start-0" placeholder="Type here..." />
              </div>
            </div>

            <div class="col-md-3">
              <button class="btn btn-primary w-100 py-2 d-flex align-items-center justify-content-center gap-2" @click="generateReport">
                <i class="bi bi-play-fill fs-5"></i> Generate Report
              </button>
            </div>
          </template>
        </div>

        <div v-if="selectedReportConfig && hasDateFilter" class="row mt-3 g-3">
          <div class="col-md-3">
            <label class="form-label small fw-bold text-muted text-uppercase">From Date</label>
            <input v-model="filters.fromDate" type="date" class="form-control" />
          </div>
          <div class="col-md-3">
            <label class="form-label small fw-bold text-muted text-uppercase">To Date</label>
            <input v-model="filters.toDate" type="date" class="form-control" />
          </div>
        </div>
      </div>
    </div>

    <!-- REPORT CONTENT -->
    <div v-if="reportLoading" class="text-center py-5">
      <div class="spinner-border text-primary" role="status"></div>
      <p class="mt-2 text-muted">Generating your report, please wait...</p>
    </div>

    <div v-else-if="reportData" class="report-content-card card shadow-sm border-0 border-top border-primary border-4">
      <div class="card-body p-0">
        <!-- Professional Header (Inside Report) -->
        <div class="report-print-header p-4 border-bottom bg-light d-none-print">
          <div class="d-flex justify-content-between align-items-start">
            <div>
              <h3 class="fw-bold m-0">{{ reportData.title }}</h3>
              <p class="text-muted mb-0 small">{{ selectedReportConfig.description }}</p>
            </div>
            <div class="text-end small">
              <div><strong>Generated By:</strong> {{ reportData.generatedBy }}</div>
              <div><strong>Generated At:</strong> {{ formatDate(reportData.generatedAt) }}</div>
              <div><strong>Total Records:</strong> {{ filteredData.length }}</div>
            </div>
          </div>
        </div>

        <div class="table-responsive">
          <table class="table table-hover align-middle mb-0" id="reportTable">
            <thead class="table-light">
              <tr>
                <th v-for="head in reportData.headers" :key="head.id" class="text-nowrap selectable-header" @click="sort(head.id)">
                  {{ head.label }}
                  <i v-if="sortKey === head.id" :class="['bi', sortOrder === 'asc' ? 'bi-sort-up' : 'bi-sort-down', 'ms-1']"></i>
                  <i v-else class="bi bi-arrow-down-up ms-1 text-muted opacity-25"></i>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(row, idx) in paginatedData" :key="idx">
                <td v-for="head in reportData.headers" :key="head.id">
                  {{ formatValue(row[head.id], head.type) }}
                </td>
              </tr>
              <tr v-if="filteredData.length === 0">
                <td :colspan="reportData.headers.length" class="text-center py-5 text-muted">No records found matching your filters.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Pagination -->
        <div class="p-3 border-top d-flex justify-content-between align-items-center bg-light">
          <div class="small text-muted">Showing {{ startIdx + 1 }} to {{ endIdx }} of {{ filteredData.length }} entries</div>
          <nav v-if="totalPages > 1">
            <ul class="pagination pagination-sm mb-0">
              <li class="page-item" :class="{ disabled: currentPage === 1 }">
                <a class="page-link" href="#" @click.prevent="currentPage--">Previous</a>
              </li>
              <li v-for="p in totalPages" :key="p" class="page-item" :class="{ active: currentPage === p }">
                <a class="page-link" href="#" @click.prevent="currentPage = p">{{ p }}</a>
              </li>
              <li class="page-item" :class="{ disabled: currentPage === totalPages }">
                <a class="page-link" href="#" @click.prevent="currentPage++">Next</a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>

    <div v-else-if="!selectedReportId" class="text-center py-5 bg-white border rounded shadow-sm">
      <i class="bi bi-file-earmark-text text-muted mb-3 d-block" style="font-size: 64px;"></i>
      <h4 class="text-muted">Ready to Generate</h4>
      <p class="text-muted">Select a report configuration from the dropdown above to begin.</p>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed, watch } from "vue"
import { useRoute } from "vue-router"
import { getReportConfigs, generateReportData, downloadDynamicReport } from "@/services/api"
import { handleError, handleSuccess } from "@/utils/error-handler"

const route = useRoute()
const reportConfigs = ref([])
const selectedReportId = ref("")
const selectedReportConfig = ref(null)
const reportData = ref(null)
const reportLoading = ref(false)

const filters = ref({
  fromDate: "",
  toDate: ""
})

const searchQuery = ref("")
const currentPage = ref(1)
const pageSize = 10
const sortKey = ref("")
const sortOrder = ref("asc")

onMounted(async () => {
  try {
    reportConfigs.value = await getReportConfigs()
    if (route.query.id) {
      selectedReportId.value = parseInt(route.query.id)
      onReportSelect()
      generateReport()
    }
  } catch (err) {
    handleError(err, "Config Load Error")
  }
})

const onReportSelect = () => {
  selectedReportConfig.value = reportConfigs.value.find(r => r.reportId === selectedReportId.value)
  reportData.value = null
  searchQuery.value = ""
}

const hasDateFilter = computed(() => {
  if (!selectedReportConfig.value) return false
  const fields = JSON.parse(selectedReportConfig.value.selectedFields)
  return fields.some(f => f.type === 'date' || f.id.toLowerCase().includes('date') || f.id.toLowerCase().includes('at'))
})

const generateReport = async () => {
  if (!selectedReportId.value) return
  
  try {
    reportLoading.value = true
    const res = await generateReportData(selectedReportId.value, { 
      filters: {}, // In a real app, map from filters.value based on config
      pageIndex: 0,
      pageSize: 1000 
    })
    reportData.value = res
    currentPage.value = 1
    handleSuccess("Report generated!")
  } catch (err) {
    handleError(err, "Generation Error")
  } finally {
    reportLoading.value = false
  }
}

const filteredData = computed(() => {
  if (!reportData.value || !reportData.value.data) return []
  
  let list = [...reportData.value.data]
  
  // Local search
  if (searchQuery.value) {
    const q = searchQuery.value.toLowerCase()
    list = list.filter(row => 
      Object.values(row).some(v => String(v).toLowerCase().includes(q))
    )
  }

  // Local Sort
  if (sortKey.value) {
    list.sort((a, b) => {
      let v1 = a[sortKey.value]
      let v2 = b[sortKey.value]
      if (v1 < v2) return sortOrder.value === "asc" ? -1 : 1
      if (v1 > v2) return sortOrder.value === "asc" ? 1 : -1
      return 0
    })
  }
  
  return list
})

const sort = (key) => {
  if (sortKey.value === key) {
    sortOrder.value = sortOrder.value === "asc" ? "desc" : "asc"
  } else {
    sortKey.value = key
    sortOrder.value = "asc"
  }
}

const totalPages = computed(() => Math.ceil(filteredData.value.length / pageSize))
const startIdx = computed(() => (currentPage.value - 1) * pageSize)
const endIdx = computed(() => Math.min(startIdx.value + pageSize, filteredData.value.length))
const paginatedData = computed(() => filteredData.value.slice(startIdx.value, endIdx.value))

const exportReport = async (format) => {
  try {
    await downloadDynamicReport(selectedReportId.value, format, {})
    handleSuccess(`Exported to ${format.toUpperCase()}`)
  } catch (err) {
    handleError(err, "Export Failed")
  }
}

const printReport = () => {
  window.print()
}

const formatDate = (dateStr) => {
  return new Date(dateStr).toLocaleString()
}

const formatValue = (val, type) => {
  if (val === null || val === undefined) return "N/A"
  if (type === 'date' || (typeof val === 'string' && val.includes('T'))) {
    return new Date(val).toLocaleDateString()
  }
  if (typeof val === 'boolean') {
    return val ? "Yes" : "No"
  }
  return val
}

watch(searchQuery, () => { currentPage.value = 1 })
</script>

<style scoped>
.report-viewer-page {
  padding: 30px;
  background: #f8fafc;
  min-height: 100vh;
}

.page-header h2 {
  color: #1e293b;
}

.card {
  border-radius: 12px;
}

.selectable-header {
  cursor: pointer;
  user-select: none;
  transition: background 0.2s;
}

.selectable-header:hover {
  background: #f1f5f9 !important;
}

.report-content-card {
  animation: slide-up 0.4s ease-out forwards;
}

@keyframes slide-up {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}

@media print {
  .page-header, .card:not(.report-content-card), .pagination, .navbar, .sidebar {
    display: none !important;
  }
  .report-viewer-page {
    padding: 0;
    margin: 0;
    background: white;
  }
  .report-content-card {
    box-shadow: none !important;
    border: none !important;
  }
  .table {
    width: 100% !important;
    border: 1px solid #dee2e6 !important;
  }
}
</style>
